INSERT INTO TB_POST
VALUES (NULL,SQ_POST.nextval, '동의보감', '허준', '한약', 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);

INSERT INTO TB_USERINFO
VALUES ('1', '1', 'Man', 'USER',NULL,'N' ,TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);
INSERT INTO TB_USERINFO
VALUES ('2', '2', 'kk', 'ADMIN',NULL,'N' ,TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);

-- 답변형 게시판 테스트
-- 1
INSERT INTO TB_REPLY_BOARD
VALUES (SQ_REPLY_BOARD.nextval, '내용', '작성자', 0, 1, 0, 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);
-- 2
INSERT INTO TB_REPLY_BOARD
VALUES (SQ_REPLY_BOARD.nextval, '내용', '작성자', 0, 2, 0, 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);
-- 3
INSERT INTO TB_REPLY_BOARD
VALUES (SQ_REPLY_BOARD.nextval, '내용', '작성자', 0, 2, 2, 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);
-- 4
INSERT INTO TB_REPLY_BOARD
VALUES (SQ_REPLY_BOARD.nextval, '내용', '작성자', 0, 2, 2, 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);
-- 5
INSERT INTO TB_REPLY_BOARD
VALUES (SQ_REPLY_BOARD.nextval, '내용', '작성자', 0, 5, 0, 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);
-- 6
INSERT INTO TB_REPLY_BOARD
VALUES (SQ_REPLY_BOARD.nextval, '내용', '작성자', 0, 5, 5, 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);
-- 7
INSERT INTO TB_REPLY_BOARD
VALUES (SQ_REPLY_BOARD.nextval, '내용', '작성자', 0, 7, 0, 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);
-- 8
INSERT INTO TB_REPLY_BOARD
VALUES (SQ_REPLY_BOARD.nextval, '내용', '작성자', 0, 8, 0, 'N', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), NULL, NULL);


COMMIT;